import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Text, Heading, Box } from '@chakra-ui/react'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>xxx</Heading>
      <Box><Text> hhfjdkhfjds </Text></Box>
    </div>
  );
}
